In [1]:
import pandas as pd
import glassdoor_scraper as gs

In [17]:
from selenium import webdriver
driver = webdriver.Chrome("/Users/svetlanamaslenkova/Documents/DS_project/chromedriver_mac64/chromedriver")

/Users/svetlanamaslenkova/anaconda3/envs/ds_salary_env/lib/python3.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object

In [24]:
from selenium.common.exceptions import NoSuchElementException, ElementClickInterceptedException
from selenium import webdriver
from selenium.webdriver.common.by import By
import time
# import pandas as pd

In [1]:
import glassdoor_scraper as gs
path = "/Users/svetlanamaslenkova/Documents/DS_project/chromedriver_mac64/chromedriver"

df = gs.get_jobs('data scientist', 'United Arab Emirates', 15, True, path, 15)

https://www.glassdoor.com/Job/united-arab-emirates-data-scientist-jobs-SRCH_IL.0,20_IN6_KO21,35.htm
job_buttons DONE, length= 29
Progress: 0/15
 x out worked
SALARY INFO--------> -1
RATING INFO--------> -1
Job Title: JUNIOR DATA SCIENTIST - Dubai, UAE
Salary Estimate: -1
Job Description: Location: Dubai, UAE (We provide visa sponsorship & relocation assistance)
Starting salary of USD 60,000 per annum - 0% tax environment
About Cobblestone Energy
Cobblestone Energy is an energy trading company specialising in the Great Britain and European wholesale electricity markets. Founded in 2017, we are part of the next generation of companies defining the future of global commodity trading.
We make use of advanced data analytics and extensive research to drive profitable decision making,
Rating: -1
Company Name: Cobblestone Energy, Dubai - UAE.
Location: Sharjah
Didnt find the size of the company
Size: -1
Founded: -1
Type of Ownership: -1
Industry: -1
Sector: -1
Revenue: -1
Competitors: -1
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
job_count =  1
Progress: 1/15
 x out failed
SALARY INFO--------> -1
RATING INFO--------> -1
Job Title: Data Analyst/ Data Scientist (UAE Nationals ONLY)
Salary Estimate: -1
Job Description: Develop a well-designed system of institutional research and intelligence, which provides the university with the capability to determine whether the objectives of its academic, student, and administrative service units, and the learning outcomes of its academic programs and courses, are being met.
Implement and maintain the system of institutional research and intelligence according to local and international accreditation requirements and best practices.
Develop regular reports to facilitate m
Rating: -1
Company Name: جامعة حمدان بن محمد الذكية
Location: Dubai
Didnt find the size of the company
Size: -1
Founded: -1
Type of Ownership: -1
Industry: -1
Sector: -1
Revenue: -1
Competitors: -1
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
job_count =  2
Progress: 2/15
 x out failed
SALARY INFO--------> -1
RATING INFO--------> 5.0
Job Title: SENIOR DATA SCIENTIST - Dubai, UAE
Salary Estimate: -1
Job Description: Employment type: Full-time & Permanent
Reports to: CEO
Location: Dubai, UAE (We provide visa sponsorship & relocation assistance)
Annual Base Salary range of 80,000 USD – 150,000 USD + performance-based bonus' - 0% tax environment + an opportunity to join our employee share scheme.
About Cobblestone Energy
Cobblestone Energy is an energy trading company specialising in the Great Britain and European wholesale electricity markets. Founded in 2017, we are part of the next generation of companies d
Rating: 5.0
Company Name: Cobblestone
5.0
Location: Dubai
Found the size of the company
Size: 1 to 50 Employees
Founded: -1
Type of Ownership: Company - Private
Industry: -1
Sector: -1
Revenue: Unknown / Non-Applicable
Competitors: -1
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
job_count =  3
Progress: 3/15
 x out failed
SALARY INFO--------> -1
RATING INFO--------> 3.5
Job Title: Data Analytics (Scientist)
Salary Estimate: -1
Job Description: Job Responsibilities
Work with stakeholders throughout the organization to identify opportunities for leveraging company data to drive business solutions.
Mine and analyze data from company databases to drive optimization and improvement of product development, marketing techniques and business strategies.
Assess the effectiveness and accuracy of new data sources and data gathering techniques.
Develop custom data models and algorithms to apply to data sets.
Use predictive modeling to increase an
Rating: 3.5
Company Name: Five Continents Technical & Industrial Services Est.
3.5
Location: Abu Dhabi
Found the size of the company
Size: 501 to 1000 Employees
Founded: -1
Type of Ownership: Company - Private
Industry: -1
Sector: -1
Revenue: Unknown / Non-Applicable
Competitors: -1
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
job_count =  4
Progress: 4/15
 x out failed
SALARY INFO--------> -1
RATING INFO--------> -1
Job Title: Data Analyst / Data Scientist (Remote)
Salary Estimate: -1
Job Description: nybl is looking for our next generation of data scientists. We pride ourselves on growing our team and are always looking for the brightest talent to join us. Attitude is the most important trait we are looking for above all else.
You will be working on transforming data into intelligence by developing innovative Artificial Intelligence (AI) solutions and integrating them with cutting-edge Internet of Things (IoT) technologies. Candidates must prove that they have the will, determination and amb
Rating: -1
Company Name: nybl
Location: Dubai
Didnt find the size of the company
Size: -1
Founded: -1
Type of Ownership: -1
Industry: -1
Sector: -1
Revenue: -1
Competitors: -1
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
job_count =  5
Progress: 5/15
 x out failed
SALARY INFO--------> -1
RATING INFO--------> 3.6
Job Title: Research Scientist
Salary Estimate: -1
Job Description: Research Scientist Position Description
General Details
Position Duration 01/02/2023 to 31/12/2026
Position Title Research Scientist or Postdoc Associate
Project Title Quantum-inspired algorithms for computational fluid dynamics:
the nuclear-industry use case
Project Supervisor Dr. Mohamed Kamel RIAHI, Assistant Professor of Mathematics mohamed[dot]riahi[_at_]ku[dot]ac[_dot_]ae
Academic
Department Mathematics Department
Rating: 3.6
Company Name: Khalifa University
3.6
Location: Abu Dhabi
Found the size of the company
Size: 501 to 1000 Employees
Founded: 2007
Type of Ownership: College / University
Industry: Colleges & Universities
Sector: Education
Revenue: Unknown / Non-Applicable
Competitors: -1
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
job_count =  6
Progress: 6/15
 x out failed
SALARY INFO--------> -1
RATING INFO--------> -1
Job Title: Data Scientist
Salary Estimate: -1
Job Description: We invite you to send us your CV/Resume to careers@ispatialtec.com iSpatialTec might be right for you if you have enough experience and skills that make you confident of contributing effectively to any of these groups. We will maintain your resume on records and will contact you when a job requirement suits your skills.

Required Basic Qualifications:
B. Sc / BE / B. Tech / M. Tech / Diploma in Computer Science or allied fields.
Desired Requirements:
Graduate degree in Data Science or another qu
Rating: -1
Company Name: iSpatial Techno Solutions
1.0
Location: Abu Dhabi
Found the size of the company
Size: 1 to 50 Employees
Founded: -1
Type of Ownership: Company - Private
Industry: -1
Sector: -1
Revenue: Unknown / Non-Applicable
Competitors: -1
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
job_count =  7
Progress: 7/15
 x out failed
SALARY INFO--------> -1
RATING INFO--------> 3.5
Job Title: Senior Data Scientist - Remote
Salary Estimate: -1
Job Description: Launched in 2019, Binance.US is the fastest growing and most integrated digital asset marketplace in the United States, powered by matching engine and wallet technologies license from the world’s largest cryptocurrency exchange - Binance. Our mission is to provide liquidity, transparency, and efficiency to financial markets by creating products that leverage crypto to unlock the power of everything. We build bridges between traditional finance and digital markets that enable growth for all—empow
Rating: 3.5
Company Name: Binance.us
3.5
Location: Dubai
Found the size of the company
Size: 501 to 1000 Employees
Founded: 2019
Type of Ownership: Company - Private
Industry: Internet & Web Services
Sector: Information Technology
Revenue: Unknown / Non-Applicable
Competitors: -1
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
job_count =  8
Progress: 8/15
 x out failed
SALARY INFO--------> -1
RATING INFO--------> -1
Job Title: Data Science - Internship (Remote)
Salary Estimate: -1
Job Description: About nybl
We are developing an Ai ecosystem that enables businesses, in any industry, to be able to deploy artificially intelligent solutions using both our platform and applications. Our technology allows anyone to build Ai solutions without writing a line of code or needing a degree in Data Science. Our ecosystem is world changing: from healthcare to agriculture, education to industry, the applications of our technology are truly limitless.&nbsp;
Data Science Internship
About the Role
nybl is
Rating: -1
Company Name: nybl
Location: Dubai
Didnt find the size of the company
Size: -1
Founded: -1
Type of Ownership: -1
Industry: -1
Sector: -1
Revenue: -1
Competitors: -1
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
job_count =  9
Progress: 9/15
 x out failed
SALARY INFO--------> -1
RATING INFO--------> -1
Job Title: Data Scientist
Salary Estimate: -1
Job Description: We are looking for an engineer with good academic record, with 1-3 years of experience in business analytics.
Experience in designing and programming databases, and performing complex statistical analysis and predictive modelling, to derive meaningful insights and actionable conclusions
Create algorithms to extract information from large data sets
Establish scalable, efficient, automated processes for model development, model validation, model implementation and large scale data analysis
Develop
Rating: -1
Company Name: Affaan Technologies
Location: Dubai
Found the size of the company
Size: Unknown
Founded: -1
Type of Ownership: Company - Private
Industry: -1
Sector: -1
Revenue: Unknown / Non-Applicable
Competitors: -1
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
job_count =  10
Progress: 10/15
 x out failed
SALARY INFO--------> -1
RATING INFO--------> -1
Job Title: Data Scientist
Salary Estimate: -1
Job Description: Number of openings | 01
Job ID | 2021-1014
Job Locations | UAE
Position Type | Full Time/Contract
Posted Date | 27/04/2021
How would you like to work in a highly dynamic Health care startup? Erniesys is looking for a Data scientist for a Healthcare startup client. The data scientist will be instrumental in advising business strategy and pricing models through extensive analysis of healthcare claims data.
Rating: -1
Company Name: ERNIESYS
Location: United Arab Emirates
Didnt find the size of the company
Size: -1
Founded: -1
Type of Ownership: -1
Industry: -1
Sector: -1
Revenue: -1
Competitors: -1
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
job_count =  11
Progress: 11/15
 x out failed
SALARY INFO--------> -1
RATING INFO--------> 5.0
Job Title: JUNIOR DATA SCIENTIST - Dubai, UAE
Salary Estimate: -1
Job Description: Location: Dubai, UAE (We provide visa sponsorship & relocation assistance)
Starting salary of USD 60,000 per annum - 0% tax environment
About Cobblestone Energy
Cobblestone Energy is an energy trading company specialising in the Great Britain and European wholesale electricity markets. Founded in 2017, we are part of the next generation of companies defining the future of global commodity trading.
We make use of advanced data analytics and extensive research to drive profitable decision making,
Rating: 5.0
Company Name: Cobblestone
5.0
Location: Dubai
Found the size of the company
Size: 1 to 50 Employees
Founded: -1
Type of Ownership: Company - Private
Industry: -1
Sector: -1
Revenue: Unknown / Non-Applicable
Competitors: -1
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
job_count =  12
Progress: 12/15
 x out failed
SALARY INFO--------> -1
RATING INFO--------> -1
Job Title: Data Scientist
Salary Estimate: -1
Job Description: Job Responsibilities
Min 4 years ofprofessional experience in .NET CORE, ASP.NET MVC, MS SQL SERVER
Strong experience working with JavaScript, and jQuery
Strong knowledge of software development, debugging and deployment tools.
Knowledge and experience of SQL Server (Any version).
Understanding of MVC, WCF, WPF, LINQ, Entity Framework and any mobile technology beneficial.
Strong interpersonal and communication skills to interact with the management and team members.
Rating: -1
Company Name: Sphere IT Consultants
Location: Dubai
Didnt find the size of the company
Size: -1
Founded: -1
Type of Ownership: -1
Industry: -1
Sector: -1
Revenue: -1
Competitors: -1
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
job_count =  13
Progress: 13/15
 x out failed
SALARY INFO--------> -1
RATING INFO--------> -1
Job Title: Senior Data Scientist
Salary Estimate: -1
Job Description: Senior Data Scientist - Onsite - Dubai, UAE - Up to USD 200,000 per annum - 0% tax environment - Visa sponsorship & Relocation assistance will be provided
DataBuzz are recruiting a Senior Data Scientist on behalf of a prestigious organisation.
As a Senior Data Scientist, you will be expected to lead development and implementation of advanced analytics solutions to support the power and gas trading operations and develop systematic trading strategies across all of markets
As a Senior Data Scienti
Rating: -1
Company Name: Databuzz Ltd
Location: Dubai
Found the size of the company
Size: Unknown
Founded: -1
Type of Ownership: Company - Public
Industry: -1
Sector: -1
Revenue: Unknown / Non-Applicable
Competitors: -1
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
job_count =  14
Progress: 14/15
 x out failed
SALARY INFO--------> -1
RATING INFO--------> 4.1
Job Title: Data Scientist (English & Arabic speaking)
Salary Estimate: -1
Job Description: Need a Data Scientist fluent in English and Arabic to be based in our office in Dubai. The person will be undertaking data collection, preprocessing and analysis, building models to address business problems and presenting information using data visualization techniques.

Key responsibilities:
Independently lead E2E Analytics projects. Act as a product owner and coach the analysts within the team
Work closely with business stakeholders to understand their goals & determine how Data analytics can
Rating: 4.1
Company Name: Times World Information Technology
4.1
Location: Dubai
Found the size of the company
Size: 51 to 200 Employees
Founded: 2005
Type of Ownership: Company - Private
Industry: Information Technology Support Services
Sector: Information Technology
Revenue: $5 to $25 million (USD)
Competitors: -1
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
job_count =  15
Progress: 15/15
Scraping terminated before reaching target number of jobs. Needed 15, got 15.

In [2]:
df

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,"JUNIOR DATA SCIENTIST - Dubai, UAE",-1,"Location: Dubai, UAE (We provide visa sponsors...",-1,"Cobblestone Energy, Dubai - UAE.",Sharjah,-1,-1,-1,-1,-1,-1,-1
1,Data Analyst/ Data Scientist (UAE Nationals ONLY),-1,Develop a well-designed system of institutiona...,-1,جامعة حمدان بن محمد الذكية,Dubai,-1,-1,-1,-1,-1,-1,-1
2,"SENIOR DATA SCIENTIST - Dubai, UAE",-1,Employment type: Full-time & Permanent\nReport...,5.0,Cobblestone\n5.0,Dubai,1 to 50 Employees,-1,Company - Private,-1,-1,Unknown / Non-Applicable,-1
3,Data Analytics (Scientist),-1,Job Responsibilities\nWork with stakeholders t...,3.5,Five Continents Technical & Industrial Service...,Abu Dhabi,501 to 1000 Employees,-1,Company - Private,-1,-1,Unknown / Non-Applicable,-1
4,Data Analyst / Data Scientist (Remote),-1,nybl is looking for our next generation of dat...,-1,nybl,Dubai,-1,-1,-1,-1,-1,-1,-1
5,Research Scientist,-1,Research Scientist Position Description\nGener...,3.6,Khalifa University\n3.6,Abu Dhabi,501 to 1000 Employees,2007,College / University,Colleges & Universities,Education,Unknown / Non-Applicable,-1
6,Data Scientist,-1,We invite you to send us your CV/Resume to car...,-1,iSpatial Techno Solutions\n1.0,Abu Dhabi,1 to 50 Employees,-1,Company - Private,-1,-1,Unknown / Non-Applicable,-1
7,Senior Data Scientist - Remote,-1,"Launched in 2019, Binance.US is the fastest gr...",3.5,Binance.us\n3.5,Dubai,501 to 1000 Employees,2019,Company - Private,Internet & Web Services,Information Technology,Unknown / Non-Applicable,-1
8,Data Science - Internship (Remote),-1,About nybl\nWe are developing an Ai ecosystem ...,-1,nybl,Dubai,-1,-1,-1,-1,-1,-1,-1
9,Data Scientist,-1,We are looking for an engineer with good acade...,-1,Affaan Technologies,Dubai,Unknown,-1,Company - Private,-1,-1,Unknown / Non-Applicable,-1
10,Data Scientist,-1,Number of openings | 01\nJob ID | 2021-1014\nJ...,-1,ERNIESYS,United Arab Emirates,-1,-1,-1,-1,-1,-1,-1
11,"JUNIOR DATA SCIENTIST - Dubai, UAE",-1,"Location: Dubai, UAE (We provide visa sponsors...",5.0,Cobblestone\n5.0,Dubai,1 to 50 Employees,-1,Company - Private,-1,-1,Unknown / Non-Applicable,-1
12,Data Scientist,-1,Job Responsibilities\nMin 4 years ofprofession...,-1,Sphere IT Consultants,Dubai,-1,-1,-1,-1,-1,-1,-1
13,Senior Data Scientist,-1,"Senior Data Scientist - Onsite - Dubai, UAE - ...",-1,Databuzz Ltd,Dubai,Unknown,-1,Company - Public,-1,-1,Unknown / Non-Applicable,-1
14,Data Scientist (English & Arabic speaking),-1,Need a Data Scientist fluent in English and Ar...,4.1,Times World Information Technology\n4.1,Dubai,51 to 200 Employees,2005,Company - Private,Information Technology Support Services,Information Technology,$5 to $25 million (USD),-1